-- CreateTable
CREATE TABLE "ComamandeToMonitor" (
    "id" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "S1" TEXT,
    "S2" TEXT,
    "S3" TEXT,
    "S4" TEXT,
    "S5" TEXT,
    "S6" TEXT,
    "S7" TEXT,
    "S8" TEXT,
    "S9" TEXT,
    "S10" TEXT,
    "S11" TEXT,
    "S12" TEXT,
    "S13" TEXT,
    "S14" TEXT,
    "S15" TEXT,
    "S16" TEXT,
    "HumMin" INTEGER,
    "HumMax" INTEGER,
    "TemMin" INTEGER,
    "TemMax" INTEGER,
    "LumMin" INTEGER,
    "LumMax" INTEGER,
    "PressMin" INTEGER,
    "PressMax" INTEGER,
    "Co2Min" INTEGER,
    "Co2Max" INTEGER,
    "param300" BOOLEAN,
    "param301" BOOLEAN,
    "param302" BOOLEAN,
    "param303" BOOLEAN,
    "param304" BOOLEAN,
    "param305" BOOLEAN,
    "param306" BOOLEAN,
    "param307" BOOLEAN,
    "param308" BOOLEAN,
    "param309" BOOLEAN,
    "param310" BOOLEAN,
    "param311" BOOLEAN,
    "param313" BOOLEAN,
    "param314" BOOLEAN,
    "param315" BOOLEAN,
    "param316" BOOLEAN,
    "PolStartTime" TEXT,
    "PolEndTime" TEXT,
    "Periode" INTEGER,
    "MomentFloraison" BOOLEAN,

    CONSTRAINT "ComamandeToMonitor_pkey" PRIMARY KEY ("id")
);
