-- CreateTable
CREATE TABLE "SensorDataForDay" (
    "id" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startTimestamp" TIMESTAMP(3) NOT NULL,
    "endTimestamp" TIMESTAMP(3) NOT NULL,
    "averageTemp" DOUBLE PRECISION,
    "averageHumidity" DOUBLE PRECISION,
    "averagePressure" DOUBLE PRECISION,
    "averageLightA" DOUBLE PRECISION,
    "averageSol" DOUBLE PRECISION,
    "averageAccX" DOUBLE PRECISION,
    "averageAccY" DOUBLE PRECISION,
    "averageAccZ" DOUBLE PRECISION,
    "averageIaq" DOUBLE PRECISION,
    "averageGyroX" DOUBLE PRECISION,
    "averageGyroY" DOUBLE PRECISION,
    "averageGyroZ" DOUBLE PRECISION,
    "lastSeuilHumidityMin" DOUBLE PRECISION,
    "lastSeuilHumidityMax" DOUBLE PRECISION,
    "lastSeuilTempMin" DOUBLE PRECISION,
    "lastSeuilTempMax" DOUBLE PRECISION,
    "lastSeuilLumMin" DOUBLE PRECISION,
    "lastSeuilLumMax" DOUBLE PRECISION,
    "lastSeuilPressionMin" DOUBLE PRECISION,
    "lastSeuilPressionMax" DOUBLE PRECISION,
    "lastSeuilCo2Min" DOUBLE PRECISION,
    "lastSeuilCo2Max" DOUBLE PRECISION,
    "lastMeanTemp" DOUBLE PRECISION,
    "lastMeanHumidity" DOUBLE PRECISION,
    "lastMeanLum" DOUBLE PRECISION,
    "lastMeanPress" DOUBLE PRECISION,
    "lastMeanCo2" DOUBLE PRECISION,
    "S1" INTEGER NOT NULL,
    "S2" INTEGER NOT NULL,
    "S3" INTEGER NOT NULL,
    "S4" INTEGER NOT NULL,
    "S5" INTEGER NOT NULL,
    "S6" INTEGER NOT NULL,
    "S7" INTEGER NOT NULL,
    "S8" INTEGER NOT NULL,
    "S9" INTEGER NOT NULL,
    "S10" INTEGER NOT NULL,
    "S11" INTEGER NOT NULL,
    "S12" INTEGER NOT NULL,
    "S13" INTEGER NOT NULL,
    "S14" INTEGER NOT NULL,
    "S15" INTEGER NOT NULL,
    "S16" INTEGER NOT NULL,
    "momentFloraison" BOOLEAN NOT NULL,

    CONSTRAINT "SensorDataForDay_pkey" PRIMARY KEY ("id")
);
